config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      post 'debfiles/upload/:token' => 'debfiles#upload'
    end
  end

  devise_for :users
  resources :debfiles do
    post 'upload', action: :upload
  end

  resources :projects do
    member do
      get 'refresh', action: :refresh
      get 'rebuild', action: :rebuild
    end
  end
  
  resources :branches do
    collection do
      post :add_packages
    end

    member do
      get 'auto_add/:package_id', action: :auto_add, as: :auto_add_package
    end
  end
  
  resources :packages

  root 'projects#index'

  get 'library' => 'library#index', as: :library
  get 'library/rescan' => 'library#rescan', as: :rescan_library

  get 'aptly' => 'aptly#index', as: :aptly

  DebianRepoServer = Proc.new do |env|
    Rack::Directory.new(Rails.root.join("aptly","public")).call(env)
  end

  mount DebianRepoServer, at: '/debian'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  serialize :auto_added_packages, Array

  belongs_to :project
  has_many :packages

  def repo_name
    "#{project.name}-#{component_name}"
  end

  def name=(val)
    super(val)
    self.component_name ||= name.parameterize
  end

  def auto_add(package_name)
    auto_added_packages = (auto_added_packages || []).push(package_name) unless auto_added?(package_name)
  end

  def stop_auto_adding(package_name)
    auto_added_packages = auto_added_packages.delete(package_name)
  end

  def auto_added?(package_name)
    auto_added_packages.include?(package_name)
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy, :add_packages, :auto_add]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    @debfiles = Debfile.all.map {|d| [d.name, d.id] }
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_packages
    service = Services::PackageAssignment.new(@branch)
    result = service.process(params[:debfile_ids])
    
    redirect_to :back, flash: result
  end

  def auto_add
    name = Package.find(params[:package_id]).name
    if @branch.auto_added?(name)
      @branch.stop_auto_adding(name)
      msg = "The package #{name} will not be automatically added anymore"
    else
      @branch.auto_add(name)
      msg = "The package #{name} will be automatically added when a new version is added to the library"
    end

    if @branch.save and @branch.auto_added?(name)
      flash = {success: msg}
    else
      flash = {error: "Failed to save the changes"}
    end

    redirect_to :back, flash: flash
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id] || params[:branch_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :project_id, :debfile_ids, :branch_id, :repo_name, :package_id)
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
 
 def branch_link(branch)
   return 'none' unless branch
   link_to branch.name, branch
 end

end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-horizontal">
    <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-2" %>
      <div class="col-sm-5">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :component_name, class: "control-label col-sm-2" %>
      <div class="col-sm-5">
        <%= f.text_field :component_name, class: 'form-control' %>
      </div>
    </div>
  </dl>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/_table.html.erb
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Project</th>
      <th>Name</th>
      <th>Packages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% (branches).each do |branch| %>
      <tr>
        <td><%= project_link branch.project %></td>
        <td><%= branch_link branch %></td>
        <td><%= branch.packages.count %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Branches</h1>

<%= render partial: 'branches/table', locals: {branches: @branches} %>

app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

app/views/branches/show.html.erb
<div class="pull-right ops button-group">
  <%= link_to glyph('edit'), edit_branch_path(@branch), class: "btn btn-sm btn-success" %>
</div>

<h1><%= @branch.name %> <small><%= link_to @branch.project.name, @branch.project %></small></h1>

You can import this branch using the following directive:

<pre>
deb http://debian.example.com/ <%= @branch.project.distribution_name %> <%= @branch.component_name %>
</pre>

<h2>Packages</h2>

<%= form_tag 'add_packages' do %>
  <%= hidden_field_tag :branch_id, @branch.id %>
  <div class="form-inline">
    <%= select_tag 'debfile_ids[]', options_for_select(@debfiles) %>
  </div>
<% end %>


<%= render partial: 'packages/table', locals: { packages: @branch.packages } %>