config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      post 'debfiles/upload/:token' => 'debfiles#upload'
    end
  end

  devise_for :users
  resources :debfiles do
    post 'upload', action: :upload
  end

  resources :projects do
    member do
      get 'refresh', action: :refresh
      get 'rebuild', action: :rebuild
    end
  end
  
  resources :branches do
    collection do
      post :add_packages
    end

    member do
      get 'auto_add/:package_id', action: :auto_add, as: :auto_add_package
    end
  end
  
  resources :packages

  root 'projects#index'

  get 'library' => 'library#index', as: :library
  get 'library/rescan' => 'library#rescan', as: :rescan_library

  get 'aptly' => 'aptly#index', as: :aptly

  DebianRepoServer = Proc.new do |env|
    Rack::Directory.new(Rails.root.join("aptly","public")).call(env)
  end

  mount DebianRepoServer, at: '/debian'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :branches

  def repo_names
    branches.map {|b| b.repo_name }
  end

  def name=(val)
    super(val)
    self.distribution_name = val.parameterize
  end

  def distribution
    self.distribution_name
  end

  def components
    branches.map {|b| b.component_name }
  end

  def repos
    branches.map {|b| b.repo_name }
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :rebuild, :refresh]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def rebuild
    strio = StringIO.new
    log   = Logger.new strio
    Services::AptlyDropper.new(@project, log).process
    Services::AptlyBuilder.new(@project, log).process
    @log  = strio.string
    render :build
  end

  def refresh
    strio = StringIO.new
    log   = Logger.new strio
    Services::AptlyBuilder.new(@project, log).process
    @log  = strio.string
    render :build
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :repo_name)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def project_link(project)
    return 'none' if project.nil?
    link_to project.name, project
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-horizontal">
    <div class="form-group">
      <%= f.label :name, class: "control-label col-sm-2" %>
      <div class="col-sm-5">
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :distribution_name, class: "control-label col-sm-2" %>
      <div class="col-sm-5">
        <%= f.text_field :distribution_name, class: 'form-control' %>
      </div>
    </div>
  </dl>


  <div class="field">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/build.html.erb
<h1>Working on repositories for <%= link_to @project.name, @project %></h1>

<p>This process will build or update the aptly structure for the project.</p>

<pre>
<%= @log %>
</pre>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<%= form_for(Project.new) do |f| %>
  <div class="form-inline">
    <%= f.text_field :name, autofocus: true, placeholder: "Project Name", class: "form-control" %>
    <%= f.submit class: "form-control btn btn-primary" %></p>
  </div>
<% end %>                                                                

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Branches</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= raw project.branches.map {|b| link_to(b.name, b) }.join(', ') %></td>
        <td>
          <%= link_to glyph('repeat')+" Rebuild", rebuild_project_path(project), class: "btn btn-xs btn-warning" %>
          <%= link_to glyph('refresh')+" Refresh", refresh_project_path(project), class: "btn btn-xs btn-info" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="pull-right ops button-group">
  <%= link_to glyph('edit'), edit_project_path(@project), class: "btn btn-success" %>
  <%= link_to glyph('repeat')+" Rebuild", rebuild_project_path(@project), class: "btn btn-warning" %>
  <%= link_to glyph('refresh')+" Refresh", refresh_project_path(@project), class: "btn btn-info" %>
</div>

<h1>Project: <%= @project.name %></h1>

This project has two branches.  You can import them all using this directive:

<pre>
deb http://debian.example.com/ <%= @project.distribution_name %> <%= @project.components.join(' ') %>
</pre>

<h2>Branches</h2>

<%= form_for(Branch.new) do |f| %>
  <div class="form-inline">
    <%= f.text_field :name, autofocus: true, placeholder: "Branch Name", class: "form-control" %>
    <%= f.submit class: "form-control btn btn-primary" %>
  </div>
  <%= f.hidden_field :project_id, value: @project.id %>
<% end %>

<%= render partial: 'branches/table', locals: { branches: @project.branches } %>