config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      post 'debfiles/upload/:token' => 'debfiles#upload'
    end
  end

  devise_for :users
  resources :debfiles do
    post 'upload', action: :upload
  end

  resources :projects do
    member do
      get 'refresh', action: :refresh
      get 'rebuild', action: :rebuild
    end
  end
  
  resources :branches do
    collection do
      post :add_packages
    end

    member do
      get 'auto_add/:package_id', action: :auto_add, as: :auto_add_package
    end
  end
  
  resources :packages

  root 'projects#index'

  get 'library' => 'library#index', as: :library
  get 'library/rescan' => 'library#rescan', as: :rescan_library

  get 'aptly' => 'aptly#index', as: :aptly

  DebianRepoServer = Proc.new do |env|
    Rack::Directory.new(Rails.root.join("aptly","public")).call(env)
  end

  mount DebianRepoServer, at: '/debian'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Debweb</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Debweb</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Projects", projects_path %></li>
              <li><%= link_to "Branches", branches_path %></li>
              <li><%= link_to "Packages", packages_path %></li>
              <li><%= link_to "Library", library_path %></li>
              <li><%= link_to "Aptly", aptly_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Signed in as #{current_user.email}", edit_user_registration_path(current_user) %></li>
            <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <%= bootstrap_flash %>

      <%= yield %>


    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>